spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-calss-name: org.h2.Driver
  h2:
    console:
      enabled: true

  jpa:
    hibername:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect

